import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#ffffff' },

  // --- AUTH SCREEN STYLES ---
  authContainer: { flex: 1, backgroundColor: '#ffffff' },
  authTopSection: { flex: 0.45, justifyContent: 'center', alignItems: 'center', backgroundColor: '#ffffff' },
  authLogoText: { fontSize: 32, fontWeight: '900', color: '#000000', marginTop: 12, letterSpacing: -1 },
  authLogoSubtext: { fontSize: 15, fontWeight: '700', color: '#000000', marginTop: 2 },
  
  authBottomSection: { flex: 0.55, backgroundColor: '#000000', borderTopLeftRadius: 32, borderTopRightRadius: 32, paddingHorizontal: 30, paddingTop: 35 },
  authWelcomeText: { fontSize: 32, fontWeight: '900', color: '#ffffff', textAlign: 'center', marginBottom: 20 },
  
  authErrorBox: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#fee2e2', padding: 12, borderRadius: 12, marginBottom: 20, gap: 8 },
  authErrorText: { color: '#dc2626', fontSize: 13, fontWeight: '600', flex: 1, lineHeight: 18 },

  authInputLabel: { fontSize: 14, fontWeight: '700', color: '#ffffff', marginBottom: 8, marginLeft: 2 },
  authInput: { backgroundColor: '#ffffff', borderRadius: 12, height: 50, paddingHorizontal: 16, fontSize: 16, color: '#000000', marginBottom: 20 },
  
  passwordInputContainer: { flexDirection: 'row', backgroundColor: '#ffffff', borderRadius: 12, height: 50, alignItems: 'center' },
  passwordInput: { flex: 1, height: '100%', paddingHorizontal: 16, fontSize: 16, color: '#000000' },
  eyeIconContainer: { paddingHorizontal: 16, height: '100%', justifyContent: 'center' },
  
  authPrimaryButton: { backgroundColor: '#ffffff', borderRadius: 25, height: 54, justifyContent: 'center', alignItems: 'center' },
  authPrimaryButtonText: { fontSize: 20, fontWeight: '900', color: '#000000' },
  
  authToggleTextContainer: { marginTop: 24, alignItems: 'center' },
  authToggleText: { color: '#ffffff', fontSize: 13, fontWeight: '600' },
  authToggleTextBold: { fontWeight: 'bold', textDecorationLine: 'underline' },

  // --- CHAT STYLES ---
  chatBubble: { maxWidth: '80%', padding: 14, borderRadius: 16, marginVertical: 4 },
  chatBubbleUser: { backgroundColor: '#000000', alignSelf: 'flex-end', borderBottomRightRadius: 4 },
  chatBubbleGemini: { backgroundColor: '#f1f5f9', alignSelf: 'flex-start', borderBottomLeftRadius: 4 },
  chatText: { fontSize: 15, lineHeight: 20 },
  chatTextUser: { color: '#ffffff' },
  chatTextGemini: { color: '#111827' },
  chatInputRow: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 12, borderTopWidth: 1, borderColor: '#e5e7eb', backgroundColor: '#ffffff' },
  chatInput: { flex: 1, backgroundColor: '#f8fafc', borderWidth: 1, borderColor: '#e2e8f0', borderRadius: 24, paddingHorizontal: 16, height: 48, fontSize: 15, color: '#111827' },
  chatSendButton: { backgroundColor: '#000000', width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center' },

  // --- MAIN APP STYLES ---
  mainContent: { flex: 1, paddingTop: 60, paddingHorizontal: 20 },
  scanContainer: { flex: 1, paddingTop: 60, paddingHorizontal: 20, backgroundColor: '#f8fafc', alignItems: 'center' },
  scanScrollView: { flex: 1, backgroundColor: '#f8fafc' },
  scanSubtitle: { fontSize: 14, color: '#6b7280', marginTop: 4, textAlign: 'center' },
  viewfinderBox: { width: '100%', height: 360, backgroundColor: '#0f172a', borderRadius: 24, marginTop: 24, position: 'relative', overflow: 'hidden' },
  cameraView: { flex: 1, width: '100%', height: '100%' },
  overlayFrame: { flex: 1, position: 'relative', margin: 24 },
  cornerMarker: { position: 'absolute', width: 24, height: 24, borderColor: '#38bdf8', borderWidth: 3 },
  topLeft: { top: 10, left: 10, borderBottomWidth: 0, borderRightWidth: 0 },
  topRight: { top: 10, right: 10, borderBottomWidth: 0, borderLeftWidth: 0 },
  bottomLeft: { bottom: 10, left: 10, borderTopWidth: 0, borderRightWidth: 0 },
  bottomRight: { bottom: 10, right: 10, borderTopWidth: 0, borderLeftWidth: 0 },
  successAlert: { flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: '#d1fae5', paddingHorizontal: 16, paddingVertical: 10, borderRadius: 12, marginTop: 16 },
  successAlertText: { color: '#065f46', fontWeight: '600', fontSize: 13 },
  scanActionsRow: { width: '100%', flexDirection: 'row', gap: 12, marginTop: 24 },
  scanPrimaryButton: { flex: 1, backgroundColor: '#000000', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', height: 52, borderRadius: 999, gap: 8 },
  scanPrimaryButtonText: { color: '#ffffff', fontWeight: '700', fontSize: 15 },
  modalBackdrop: { flex: 1, backgroundColor: 'rgba(0, 0, 0, 0.5)', justifyContent: 'center', padding: 20 },
  modalContent: { backgroundColor: '#ffffff', borderRadius: 24, padding: 20, maxHeight: '85%', shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.15, shadowRadius: 12, elevation: 5 },
  errorHeaderContainer: { flexDirection: 'row', alignItems: 'flex-start', gap: 10, paddingRight: 10 },
  errorTitleText: { fontSize: 16, fontWeight: '700', color: '#dc2626', flexShrink: 1, flexWrap: 'wrap', lineHeight: 22 },
  errorSubtitle: { fontSize: 13, color: '#6b7280', marginTop: 6, lineHeight: 18 },
  photoPickerRow: { flexDirection: 'row', alignItems: 'center', gap: 12, marginTop: 6 },
  previewThumbnail: { width: 52, height: 52, borderRadius: 12 },
  placeholderThumbnail: { width: 52, height: 52, borderRadius: 12, backgroundColor: '#f1f5f9', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#e2e8f0' },
  photoPickerButton: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: '#f1f5f9', paddingHorizontal: 16, height: 44, borderRadius: 12, flex: 1 },
  photoPickerButtonText: { fontSize: 12, fontWeight: '600', color: '#111827' },
  inputLabel: { fontSize: 12, fontWeight: '600', color: '#374151', marginTop: 14, marginBottom: 4 },
  modalInput: { borderWidth: 1, borderColor: '#d1d5db', borderRadius: 12, paddingHorizontal: 14, height: 48, fontSize: 15, color: '#111827' },
  modalButtonRow: { flexDirection: 'row', gap: 12, marginTop: 20 },
  modalCancelButton: { flex: 1, borderWidth: 1, borderColor: '#d1d5db', height: 48, borderRadius: 999, alignItems: 'center', justifyContent: 'center' },
  modalCancelText: { color: '#374151', fontWeight: '600' },
  modalSaveButton: { flex: 1, backgroundColor: '#000000', height: 48, borderRadius: 999, alignItems: 'center', justifyContent: 'center' },
  modalSaveText: { color: '#ffffff', fontWeight: '600' },
  homeContainer: { flex: 1, backgroundColor: '#f8fafc' },
  headerBlock: { backgroundColor: '#000000', height: 220, paddingTop: 60, paddingHorizontal: 24, borderBottomLeftRadius: 28, borderBottomRightRadius: 28, position: 'relative', overflow: 'hidden' },
  homeHeaderRow: { flexDirection: 'row', alignItems: 'center', gap: 12, zIndex: 2, marginBottom: 12 },
  homeHeaderAvatar: { width: 44, height: 44, borderRadius: 22 },
  homeHeaderAvatarPlaceholder: { width: 44, height: 44, borderRadius: 22, backgroundColor: '#333333', alignItems: 'center', justifyContent: 'center' },
  homeHeaderAvatarText: { color: '#ffffff', fontSize: 14, fontWeight: 'bold' },
  headerWelcomeText: { fontSize: 28, fontWeight: '800', color: '#ffffff', zIndex: 2 },
  headerAbstractArt: { position: 'absolute', bottom: 0, zIndex: 1, alignSelf: 'center' },
  headerAccentLeft: { position: 'absolute', bottom: 0, left: 0, zIndex: 1 },
  headerAccentRight: { position: 'absolute', bottom: 0, right: 0, zIndex: 1 },
  subHeaderRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  backButton: { padding: 4 },
  totalValueBanner: { backgroundColor: '#000000', borderRadius: 16, padding: 20, marginTop: 16, alignItems: 'center', justifyContent: 'center' },
  totalBannerLabel: { fontSize: 12, fontWeight: '700', color: '#94a3b8', letterSpacing: 0.5, textTransform: 'uppercase' },
  totalBannerAmount: { fontSize: 32, fontWeight: 'bold', color: '#ffffff', marginTop: 4 },
  homeBody: { paddingHorizontal: 16, paddingTop: 16 },
  homeSearchBar: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e2e8f0', borderRadius: 999, paddingHorizontal: 18, height: 54, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.05, shadowRadius: 4, elevation: 2, marginBottom: 8 },
  homeSearchInput: { flex: 1, fontSize: 16, color: '#111827', marginLeft: 10 },
  metricsRow: { flexDirection: 'row', gap: 12, marginTop: 12 },
  metricCard: { flex: 1, backgroundColor: '#000000', borderRadius: 16, padding: 16, height: 120, justifyContent: 'space-between', shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.1, shadowRadius: 6, elevation: 3 },
  metricCardHeader: { fontSize: 10, fontWeight: '700', color: '#94a3b8', letterSpacing: 0.5 },
  metricValue: { fontSize: 26, fontWeight: 'bold', color: '#ffffff' },
  metricSub: { fontSize: 12, color: '#94a3b8' },
  sectionHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 24, marginBottom: 10 },
  sectionHeading: { fontSize: 16, fontWeight: '700', color: '#111827' },
  viewAllText: { fontSize: 13, fontWeight: '600', color: '#6366f1' },
  itemCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#ffffff', borderRadius: 16, padding: 12, marginBottom: 10, borderWidth: 1, borderColor: '#f1f5f9', shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.03, shadowRadius: 3, elevation: 1 },
  itemThumbPlaceholder: { width: 48, height: 48, borderRadius: 10, backgroundColor: '#e2e8f0' },
  itemThumbImage: { width: 48, height: 48, borderRadius: 10 },
  itemInfo: { flex: 1, marginLeft: 12 },
  itemName: { fontSize: 14, fontWeight: '600', color: '#111827' },
  itemDate: { fontSize: 12, color: '#94a3b8', marginTop: 2 },
  pillExpiring: { backgroundColor: '#fef3c7', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 999 },
  pillExpiringText: { fontSize: 11, fontWeight: '700', color: '#d97706' },
  pillExpired: { backgroundColor: '#fee2e2', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 999 },
  pillExpiredText: { fontSize: 11, fontWeight: '700', color: '#dc2626' },
  title: { fontSize: 30, fontWeight: '800', color: '#111827' },
  searchBar: { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e5e7eb', borderRadius: 999, paddingHorizontal: 16, height: 52, marginTop: 20 },
  searchInput: { flex: 1, fontSize: 15, color: '#111827' },
  chipsRow: { height: 44, flexGrow: 0, marginTop: 16 },
  chipsContent: { alignItems: 'center', gap: 8 },
  chip: { paddingHorizontal: 18, paddingVertical: 9, borderRadius: 999, borderWidth: 1, borderColor: '#e5e7eb', backgroundColor: '#ffffff' },
  chipActive: { backgroundColor: '#111827', borderColor: '#111827' },
  chipText: { fontSize: 14, fontWeight: '500', color: '#374151' },
  chipTextActive: { color: '#ffffff' },
  carouselContainer: { marginTop: 16, marginBottom: 8 },
  heroCard: { width: 260, height: 200, borderRadius: 20, overflow: 'hidden', backgroundColor: '#e2e8f0', position: 'relative' },
  heroImagePlaceholder: { width: '100%', height: '100%', backgroundColor: '#cbd5e1' },
  heroImage: { width: '100%', height: '100%' },
  heroOverlay: { position: 'absolute', bottom: 0, left: 0, right: 0, height: '45%', backgroundColor: 'rgba(0, 0, 0, 0.45)', justifyContent: 'center', paddingHorizontal: 16 },
  heroTitle: { color: '#ffffff', fontSize: 18, fontWeight: '700' },
  heroBrand: { color: '#cbd5e1', fontSize: 13, fontWeight: '500', marginTop: 2 },
  sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 16, marginBottom: 14 },
  sectionTitle: { fontSize: 18, fontWeight: '700', color: '#111827' },
  row: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#f1f5f9', borderRadius: 16, padding: 12, gap: 12 },
  thumb: { width: 52, height: 52, borderRadius: 12, backgroundColor: '#e2e8f0' },
  thumbImage: { width: 52, height: 52, borderRadius: 12 },
  rowBody: { flex: 1 },
  rowTitle: { fontSize: 15, fontWeight: '600', color: '#111827' },
  rowMeta: { fontSize: 13, color: '#94a3b8', marginTop: 2 },
  priceContainer: { alignItems: 'flex-end' },
  itemPriceText: { fontSize: 15, fontWeight: '700', color: '#111827' },
  statusPill: { paddingHorizontal: 10, paddingVertical: 5, borderRadius: 999 },
  statusText: { fontSize: 11, fontWeight: '700', letterSpacing: 0.5 },
  emptyContainer: { alignItems: 'center', justifyContent: 'center', marginTop: 50, marginBottom: 30, paddingHorizontal: 20 },
  emptyTitle: { fontSize: 18, fontWeight: '700', color: '#111827', marginTop: 12 },
  emptyText: { textAlign: 'center', color: '#6b7280', marginTop: 6, fontSize: 14 },
  tabBar: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-around', backgroundColor: '#ffffff', height: 57, borderTopLeftRadius: 24, borderTopRightRadius: 24, borderTopWidth: 1, borderColor: '#e5e7eb', shadowColor: '#000000', shadowOffset: { width: 0, height: -6 }, shadowOpacity: 0.12, shadowRadius: 12, elevation: 10, paddingBottom: 4 },
  tabItem: { flex: 1, alignItems: 'center', justifyContent: 'center', height: '100%' },
  
  // Custom Monochromatic Switch
  customSwitchTrack: { width: 48, height: 26, borderRadius: 13, borderWidth: 2, justifyContent: 'center', backgroundColor: '#f9fafb' },
  customSwitchKnob: { width: 18, height: 18, borderRadius: 9 },

  // Category Selection Chips
  categoryDropdownContainer: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 6 },
  categoryChip: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 8, backgroundColor: '#f1f5f9', borderWidth: 1, borderColor: '#e2e8f0' },
  categoryChipSelected: { backgroundColor: '#000000', borderColor: '#000000' },
  categoryChipText: { fontSize: 13, fontWeight: '600', color: '#374151' },
  categoryChipTextSelected: { color: '#ffffff' },

  // Profile Screen Styles
  profileCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#f8fafc', borderRadius: 20, padding: 20, marginTop: 20, borderWidth: 1, borderColor: '#e2e8f0' },
  profileAvatarContainer: { width: 64, height: 64, borderRadius: 32, backgroundColor: '#000000', alignItems: 'center', justifyContent: 'center' },
  profileAvatarImage: { width: 64, height: 64, borderRadius: 32 },
  profileAvatarText: { color: '#ffffff', fontSize: 20, fontWeight: 'bold' },
  profileInfo: { marginLeft: 16, flex: 1 },
  profileName: { fontSize: 18, fontWeight: '700', color: '#111827' },
  profileEmail: { fontSize: 13, color: '#6b7280', marginTop: 2 },
  profileSectionHeader: { fontSize: 14, fontWeight: '700', color: '#4b5563', marginTop: 24, marginBottom: 8, textTransform: 'uppercase', letterSpacing: 0.5 },
  profileSectionGroup: { backgroundColor: '#ffffff', borderRadius: 16, borderWidth: 1, borderColor: '#e5e7eb', overflow: 'hidden' },
  profileRowItem: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 14, paddingHorizontal: 16, borderBottomWidth: 1, borderBottomColor: '#f1f5f9' },
  profileRowLeft: { flexDirection: 'row', alignItems: 'center', gap: 12, flex: 1 },
  profileRowText: { fontSize: 15, fontWeight: '500', color: '#111827' },
  profileVersionText: { fontSize: 13, color: '#9ca3af', fontWeight: '500' },
  logoutButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, backgroundColor: '#fee2e2', borderRadius: 16, height: 50, marginTop: 30 },
  logoutButtonText: { color: '#dc2626', fontWeight: '700', fontSize: 15 },
  settingToggleRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: '#ffffff', padding: 16, borderRadius: 16, borderWidth: 1, borderColor: '#e5e7eb' },
  settingToggleText: { fontSize: 15, fontWeight: '600', color: '#111827' },
  settingToggleSubtext: { fontSize: 13, color: '#6b7280', marginTop: 4 },
  exportDataButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#dc2626', borderRadius: 16, height: 50, marginTop: 10 },
  exportDataButtonText: { color: '#dc2626', fontWeight: '600', fontSize: 14 },
  faqCard: { backgroundColor: '#ffffff', padding: 16, borderRadius: 16, borderWidth: 1, borderColor: '#e5e7eb' },
  faqTitle: { fontSize: 15, fontWeight: '700', color: '#111827', marginBottom: 6 },
  faqBody: { fontSize: 14, color: '#4b5563', lineHeight: 20 },
  editAvatarWrapper: { alignItems: 'center', marginTop: 30, marginBottom: 10 },
  editAvatarContainer: { width: 100, height: 100, borderRadius: 50, backgroundColor: '#0f172a', alignItems: 'center', justifyContent: 'center', position: 'relative' },
  editAvatarImage: { width: 100, height: 100, borderRadius: 50 },
  editAvatarInitials: { color: '#ffffff', fontSize: 32, fontWeight: 'bold' },
  editAvatarBadge: { position: 'absolute', bottom: 0, right: 0, backgroundColor: '#000000', width: 32, height: 32, borderRadius: 16, alignItems: 'center', justifyContent: 'center', borderWidth: 2, borderColor: '#ffffff' },
  editAvatarHint: { fontSize: 13, color: '#6b7280', marginTop: 12, fontWeight: '500' },
  
  // Alert Days Selector
  daysSelectorContainer: { backgroundColor: '#ffffff', padding: 16, borderRadius: 16, borderWidth: 1, borderColor: '#e5e7eb' },
  daysSelectorTitle: { fontSize: 15, fontWeight: '600', color: '#111827', marginBottom: 12 },
  daysSelectorRow: { flexDirection: 'row', justifyContent: 'space-between', gap: 8 },
  dayChip: { flex: 1, alignItems: 'center', paddingVertical: 10, borderRadius: 8, backgroundColor: '#f1f5f9', borderWidth: 1, borderColor: 'transparent' },
  dayChipActive: { backgroundColor: '#000000', borderColor: '#000000' },
  dayChipText: { fontSize: 14, fontWeight: '600', color: '#4b5563' },
  dayChipTextActive: { color: '#ffffff' },
});
